Added onChanged notifier
4Q-s-r-o/signature pull request #7
Opened 2019-04-07 16:43 UTC by danvick

Hi guys,
I propose adding an `onChanged` notifier function of type `ValueChanged<List<Point>>` that will fire when the signature pad is cleared and `onPointerUp`.

Possible use for this would be to enable one to embed the signature pad inside a `FormField` in a flutter `Form`. I would especially like to use this awesome plugin in my [flutter_form_builder package](https://pub.dartlang.org/packages/flutter_form_builder/versions/3.0.0-beta.2) to allow having a signature pad inside a form

2019-05-20 09:46 UTC, MartinHlavna requested changes
Requested new parameter be optional

2019-05-20 09:46 UTC, MartinHlavna commented on lib/signature.dart
> +    this.onChanged,
IMHO onChanged should be optional as not everyone needs to use it.

2019-05-20 09:46 UTC, MartinHlavna commented on lib/signature.dart
> +    widget.onChanged(_points);
IMHO onChanged should be optional as not everyone needs to use it. That means this line should use null-safe operator (`?.`)

2019-05-20 09:46 UTC, MartinHlavna commented on lib/signature.dart
> +          widget.onChanged(_points);
IMHO onChanged should be optional as not everyone needs to use it. That means this line should use null-safe operator (`?.`)

2019-06-12 07:58 UTC, danvick commented
Hi @MartinHlavna, 
The change has been effected.

2019-08-05 07:59 UTC, merged